
export const ROLES = { STUDENT: "STUDENT", FACULTY, STAFF, ADMIN: "ADMIN" };
export const RESOURCE_TYPES = { LAB: "LAB", CLASSROOM, EVENT_HALL: "EVENT_HALL" };
export const BOOKING_STATUSES = { PENDING: "PENDING", APPROVED, REJECTED, CANCELLED, AUTO_CANCELLED, COMPLETED: "COMPLETED" };
export const APPROVAL_STATUSES = { PENDING: "PENDING", APPROVED, REJECTED: "REJECTED" };
export const ACCOUNT_STATUSES = { ACTIVE: "ACTIVE", INACTIVE: "INACTIVE" };
export const TIME_RANGES = { TODAY: "TODAY", THIS_WEEK, THIS_MONTH, ALL_TIME: "ALL_TIME" };
export const OVERRIDE_TYPES = { HOLIDAY: "HOLIDAY", WORKING_DAY: "WORKING_DAY" };
export const APPROVAL_TYPES = { AUTO_APPROVE: "AUTO_APPROVE", STAFF_APPROVE, ADMIN_APPROVE: "ADMIN_APPROVE" };
